FROM    golang@sha256:0b55ab82ac2a54a6f8f85ec8b943b9e470c39e32c109b766bbc1b801f3fa8d3b as builder

WORKDIR /opt/unityexporter
ADD     go.mod go.sum ./
RUN     go mod download
COPY    . .

RUN     CGO_ENABLED=0 GOOS=linux go build main.go utils.go unitycollector.go

FROM    scratch
RUN     mkdir -p /opt/unityexporter
WORKDIR /opt/unityexporter
COPY    --from=builder /opt/unityexporter/main /opt/unityexporter/main
RUN     chown -R 1000 /opt/unityexporter && chmod uga+x /opt/unityexporter/main
USER    1000
EXPOSE  8080

CMD     ["/opt/unityexporter/main"]